newportolio/budget/urls.py
from django.urls import path 
from . import views
app_name = 'budget'
urlpatterns = [
path('', views.index, name='home'),
path('budget/', views.BudgetListView.as_view(), name='budget_list'),
path('budgetDetails/<uuid:pk>/', views.BudgetDetailView.as_view(), name='budget_detail'),
path('budgetCreate/', views.BudgetCreateView.as_view(), name='budget_create'),
path('budgetUpdate/<uuid:pk>/update/', views.BudgetUpdateView.as_view(), name='budget_update'),
path('budgetDelete/<uuid:pk>/delete/', views.BudgetDeleteView.as_view(), name='budget_delete'),
path('budget/budgetResults', views.SearchResultsList.as_view(), name='search'),
path('budget/signup/', views.SignupAsView.as_view(), name='signup'),

path('LeaveMessage/', views.BusinessCreateView.as_view(), name='business_create'),

#begin savings goals views
path('savings-goals/', views.SavingsGoalListView.as_view(), name='savings-goals'),
path('savings-goals-detail/<uuid:pk>/', views.SavingsGoalsDetailView.as_view(), name='savings-goals-detail'),

#begin savings goal crud urls
path('savings-goals-create/', views.SavingsGoalCreate.as_view(), name='savings-goals-create'),
path('savings-goals/<uuid:pk>/update/', views.SavingsGoalUpdate.as_view(), name='savings-goals-update'),
path('savings-goals-delete/<uuid:pk>/delete/', views.SavingsGoalDelete.as_view(), name='savings-goals-delete'),

#begin debt urls
path('debt/', views.DebtListView.as_view(), name='debt-list'),
path('debt/<uuid:pk>/detail/', views.DebtDetailView.as_view(), name='debt-detail'),

#begin debt crud views
path('debt-create/', views.DebtCreate.as_view(), name='debt-create'),
path('debt-update/<uuid:pk>/update/', views.DebtUpdate.as_view(), name='debt-update'),
path('debt-delete/<uuid:pk>/delete/', views.DebtDelete.as_view(), name='debt-delete'),




]

newportolio/newportolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newportolio/budget/models.py
from django.db import models
import uuid 
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from math import ceil
import math



# Create your models here.
#todo's add a debt and assets model
class Debt(models.Model):
    id = models.UUIDField(primary_key=True, default= uuid.uuid4, null=False, blank=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, help_text="Enter debt type or bill type")
    amount = models.IntegerField(help_text="enter amount owed")
    creation_date = models.DateField(auto_now_add=True)
    deadline = models.DateField(default=timezone.now())
    

    class Meta:
        pass

    def __str__(self):
        return self.name
    def get_absolute_url(self):
         return reverse("budget:debt-detail", args=[str(self.id)])
    
    def month_counter(self):
        if self.deadline is not None:
            months_diff = ceil((self.deadline - self.creation_date).days / 30)
            return months_diff
        
    def payment_maker(self):
        if self.deadline is not None:
            months_diff = ceil((self.deadline - self.creation_date).days / 30)
            if months_diff != 0:
                how_much_each_month = self.amount / months_diff
                how_much_each_month = int(how_much_each_month)
            else:
                how_much_each_month = self.amount / 1
            return how_much_each_month
            


    
#class representing a single savings goal
class SavingsGoal(models.Model):
     id = models.UUIDField(primary_key=True, default= uuid.uuid4, null=False, blank=False)
     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
     name = models.CharField(max_length=100, help_text="Name your savings goal.")

     goal = models.IntegerField(help_text="Savings Goal",)
     creation_date = models.DateField(auto_now_add=True)
     deadline = models.DateField(default=timezone.now(), help_text="When do you want to reach your saving's goal?")

    
     class Meta:
         pass
     def __str__(self):
         return f'{self.name}'
     def get_absolute_url(self):
         return reverse("budget:savings-goals-detail", args=[str(self.id)])
     def get_total(self):
         total = self.goal
         return total
     
     def deadline_reached_month(self):
        if self.deadline is not None:
            months_diff = ceil((self.deadline - self.creation_date).days / 30)
            return months_diff
    
     def how_much_each_month(self):
        if self.deadline is not None:
            months_diff = ceil((self.deadline - self.creation_date).days / 30)
            if months_diff != 0:
                how_much_each_month = self.goal / months_diff
                how_much_each_month = math.ceil(how_much_each_month)
            else:
                how_much_each_month = self.goal / 1
                how_much_each_month = int(how_much_each_month)
            return how_much_each_month
     def goal_reached(self):
         if self.goal == 0:
            return "goal has been reached!!!"
         else:
             return self.goal

         
    
#class representing a single budget
class Budget(models.Model):
    id = models.UUIDField(primary_key=True, default= uuid.uuid4, null=False, blank=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, help_text="Use the tab keys for quick completion.")
    expenses = models.IntegerField(help_text="Enter  0 if recording income")
    income = models.IntegerField(help_text="Enter 0 if recording an expense")
    creation_date = models.DateField(auto_now_add=True)
    is_monthly = models.BooleanField(default=False, help_text="Is this income/expense a weekly fixed or one time event?")
    is_weekly = models.BooleanField(default=False, help_text="Is this income/expense a weekly fixed or one time event?")

    class Meta:
        pass
    def __str__(self):
        return f'{self.name}'
    def get_absolute_url(self):
        return reverse("budget:budget_detail", args=[str(self.id)])
    
    def get_total(self):
        #gets totoal for a single row, or model instance
        total = self.income - self.expenses
        return total
    

    def after_tax(self):
        total = self.income - self.expenses
        after_tax = total - total * .10
        if after_tax > 0:
            return int(after_tax)
        else:
            message = "No taxable income"
            return message
    
    def savings(self):
        total = self.income - self.expenses
        savings =  int(total *.20)
        return savings
    
    def yearly_income(self):
        if self.expenses is not None:
            if self.is_monthly == True:
                yearly_income = self.income * 12
                return yearly_income
            else:
                return 0
        
    def yearly_expenses(self):
        if self.expenses is not None:
            if self.is_monthly == True:

                cost = self.expenses * 12
                yearly = int(cost)
                return yearly
            else:
                return 0
            
    def yearly_net(self):
        if self.income is not None:
            if self.expenses is not None:
                yearly_income = self.income * 12
                yearly_expenses = self.expenses * 12

                yearly_net = yearly_income - yearly_expenses
                
                return yearly_net
            else:
                return 0
            
    def yearly_tax(self):
        if self.income is not None:
            yearly_income = self.income * 12

            yearly_tax = yearly_income * .10
            yearly_tax = int(yearly_tax)
            return yearly_tax
        else:
            return 0
        
        
    
    def debt(self):
        total = self.income - self.expenses
        amount = total * .10
        if amount > 0:
            return round(amount)
        else: 
            message = "expenses exceed income"
            return message
        
    # calc percentage of expenses
    def totalpercent(self):
        if self.income is not None:
            if self.expenses is not None:
                total = self.income - self.expenses

                percent = total / self.expenses
                
                return percent
    
    
class BusinessMessage(models.Model):
        id = models.UUIDField(primary_key=True, default=uuid.uuid4, null=False, blank=False)
        email = models.EmailField(primary_key=False, help_text="Enter business email")
        phone = models.IntegerField(null=False, blank=False, help_text="Enter business phone number")
        message = models.TextField(null=True, blank=True, help_text='leave a brief message for clients')
        class Meta:
            ordering = ['email']

        def __str__(self):
            return f'{self.email}'
    
        def get_absolute_url(self):
            pass

newportolio/budget/templates/budget/debt/debt_create.html
{% extends "budget/index.html"%}

{% block content %}


{% if user.is_subscribed %}
<br>
<div class="container-fluid text-center">

  

    
<form action="" class="form-inline-responsive bg-dark text-light" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table text-light btn-outline-info table-striped table-lg bg-dark">
        {{form.as_table}}
    </table>
   
    <input type="submit" class="btn btn-primary" value="Submit">
    
    
</form>
<script>
  const table = document.querySelector('table');

  
</script>
        
      </div>
    </div>
  </div>
</div>




</div>
<script>
    const name = document.getElementById('id_name');
    const income = document.getElementById('id_amount');
    date = document.querySelector('#id_deadline');
    date.setAttribute("type", "date");
    
    
    
    income.classList.add("btn-outline-success");
    name.classList.add("btn-outline-success");
    name.focus();
    </script>




{%else %}
<p>Not subscribed</p>
{%endif%}
{% endblock %}

newportolio/budget/templates/budget/debt/debt_delete.html
{% extends "budget/index.html"%}
{% block content %}

{% load static %}


{% block styles%}
<link rel="stylesheet" href="{% static 'css/grid.css' %}" />
{% endblock %}

{% if user.is_subscribed %}



<br>

<div class="container text-center">
    <h3>Delete DEBT: {{debt.name}}</h3>
   
    <div class="row">
      <div class="col-12 col-md-8 fs-2">Created on: {{debt.creation_date}}</div>
      <div class="col-12 col-md-8 fs-2">name: {{debt.deadline}}</div>
            <div class="col-12 col-md-8 fs-2">name: {{debt.goal}}</div>



      <div class="col-12 col-md-8 fs-2">name: {{debt.goal}}</div>

   


      



  

    <hr>
    <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        
        {{form.as_table}}
       
        <div class="col-6 col-md-4"> <input class=" btn btn-danger" type="submit" value="Yes, delete."></div>
        
    </form>
<script>
  const table = document.querySelector('table');
  table.classList.add('table-responsive')
</script>


  </div> <!-- /container -->

</div>
</div>
{%else %}
<p class="Danger">You are not subscribed and shouldn't here :()
</p>
{% endif%}





{% endblock %}

newportolio/budget/templates/budget/debt/debt_detail.html
{% extends "budget/index.html"%}

{% block content %}
{% load static %}
{% load humanize %}



{% if debt %}

<div class="container text-center">
  <h3>{{debt.name}}</h3>
  
  <div class="row">
    <div class="col-6 col-md-4"><a href="{% url 'budget:debt-update' debt.id %}">Update Budget</a></div>
    <div class="col-6 col-md-4"><a href="{% url 'budget:debt-delete' debt.id %}">Delete Budget</a></div>




  </div>
  <div class="col-12 col-md-8"><a href="{% url 'budget:debt-list'%}">Go back?</a></div>
<br>
</div>

{% else %}
<p> no debt has been created.</p>
<a href="{% url 'budget:debt-create'%}">Create debt items to get started</a>


{%endif%}




{% endblock %}

newportolio/budget/templates/budget/debt/debt_list.html
{% extends "budget/index.html"%}
{% block content %}
<section class="features">
{% if debt %}
<div style="width: 800px; margin: 40px auto; background-color: #f9f9f9; padding: 20px; border: 1px solid #ddd; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
  <h2 style="margin-top: 0;">Debt List Items</h2>
  <table id="budget-table" style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
    <thead>
      <tr style="background-color: #f0f0f0; border-bottom: 1px solid #ddd;">
        <th style="padding: 10px; text-align: left; cursor: pointer;" onclick="sortTable(0)">Name</th>
        <th style="padding: 10px; text-align: left; cursor: pointer;" onclick="sortTable(1)">Amount</th>
        <th style="padding: 10px; text-align: left; cursor: pointer;" onclick="sortTable(2)">Payments</th>
      </tr>
    </thead>
    <tbody>
   
      {% for d in debt%}
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><a href="{{d.get_absolute_url}}">{{d.name}}</a></td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">{{d.amount}}</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">{{d.payment_maker}}</td>

      </tr>
      {%endfor%}
      
    </tbody>
  </table>
  <div style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ddd;">
    <h3 style="margin-top: 0;">Totals:</h3>
    <p style="margin-bottom: 10px;">Net Income: {{overall_total}}</p>
    <p style="margin-bottom: 10px;">Debt Total: {{debt_total}}</p>
    <p style="margin-bottom: 10px;">Savings Goals: {{savings_goal}}</p>
  </div>
</div>

      {%else %}
      <p>No debt is being tracked.</p>


      {% endif %}


{% endblock content %}