newportolio/budget/urls.py
from django.urls import path 
from . import views
app_name = 'budget'
urlpatterns = [
path('', views.index, name='home'),
path('budget/', views.BudgetListView.as_view(), name='budget_list'),
path('budgetDetails/<uuid:pk>/', views.BudgetDetailView.as_view(), name='budget_detail'),
path('budgetCreate/', views.BudgetCreateView.as_view(), name='budget_create'),
path('budgetUpdate/<uuid:pk>/update/', views.BudgetUpdateView.as_view(), name='budget_update'),
path('budgetDelete/<uuid:pk>/delete/', views.BudgetDeleteView.as_view(), name='budget_delete'),
path('budget/budgetResults', views.SearchResultsList.as_view(), name='search'),
path('budget/signup/', views.SignupAsView.as_view(), name='signup'),

path('LeaveMessage/', views.BusinessCreateView.as_view(), name='business_create'),

#begin savings goals views
path('savings-goals/', views.SavingsGoalListView.as_view(), name='savings-goals'),
path('savings-goals-detail/<uuid:pk>/', views.SavingsGoalsDetailView.as_view(), name='savings-goals-detail'),

#begin savings goal crud urls
path('savings-goals-create/', views.SavingsGoalCreate.as_view(), name='savings-goals-create'),
path('savings-goals/<uuid:pk>/update/', views.SavingsGoalUpdate.as_view(), name='savings-goals-update'),
path('savings-goals-delete/<uuid:pk>/delete/', views.SavingsGoalDelete.as_view(), name='savings-goals-delete'),

#begin debt urls
path('debt/', views.DebtListView.as_view(), name='debt-list'),
path('debt/<uuid:pk>/detail/', views.DebtDetailView.as_view(), name='debt-detail'),

#begin debt crud views
path('debt-create/', views.DebtCreate.as_view(), name='debt-create'),
path('debt-update/<uuid:pk>/update/', views.DebtUpdate.as_view(), name='debt-update'),
path('debt-delete/<uuid:pk>/delete/', views.DebtDelete.as_view(), name='debt-delete'),




]

newportolio/newportolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('budget.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newportolio/budget/views.py
from django.shortcuts import render
from .models import Budget, BusinessMessage, SavingsGoal, Debt
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Sum
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import Permission
from django.contrib.auth.models import User 
from math import ceil
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, AuthenticationForm

# Create your views here.

def index(request):
    num_bud = Budget.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_bud': num_bud,
        'num_visits': num_visits,
    }

    return render(request, 'budget/index.html', context=context)

class BudgetListView(LoginRequiredMixin,generic.ListView):
    model = Budget
    context_object_name = 'budget'
    template_name = 'budget/budget_list.html'

    def get_queryset(self):
            return Budget.objects.filter(user=self.request.user).order_by('-income')
        
    def get_context_data(self, **kwargs):
        #call base
       
        context = super().get_context_data(**kwargs)
        #lets use the sessions framework to track views to this page
        #add custom query to pass in
        income = Budget.objects.all().filter(user=self.request.user).aggregate(Sum('income')).pop('income__sum')
        expenses = Budget.objects.all().filter(user=self.request.user).aggregate(Sum('expenses')).pop('expenses__sum')
        context['qs'] = Budget.objects.all().filter(user=self.request.user)
        savings_goal = SavingsGoal.objects.all().filter(user=self.request.user).aggregate(Sum('goal')).pop('goal__sum')
        debt_total = Debt.objects.all().filter(user=self.request.user).aggregate(Sum('amount')).pop('amount__sum')
        if debt_total is not None:
            context['debt_total'] = debt_total
        else:
            context['debt_total'] = 0

        if savings_goal is not None:
            context['savings_goal'] = savings_goal
        else:
            context['savings_goal'] = 0
            
        if income is not None:
            if expenses is not None:
                total = int(income - expenses)
                        
                     
                context["overall_total"] = total
                context['expenses'] = expenses
                context['income'] = income
                        

                return context
        
            else:
                context['overall_total'] = 0
                
                return context
class BudgetDetailView(LoginRequiredMixin,generic.DetailView):
    model = Budget
    
    context_object_name = 'budget'
    template_name = 'budget/budget_detail.html'

    def get_queryset(self):
        return Budget.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        

        return context
    
    
class BudgetCreateView(LoginRequiredMixin,CreateView):
    model = Budget
    
    fields = ['name', 'income', 'expenses', 'is_monthly', 'is_weekly']
    success_url = reverse_lazy('budget:budget_list')
    template_name = 'budget/budget_create.html'
    
    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(BudgetCreateView, self).form_valid(form)
    
class BudgetUpdateView(LoginRequiredMixin,UpdateView):
    model = Budget
   
    fields = ['name', 'income', 'expenses', 'is_monthly', 'is_weekly']
    template_name = 'budget/budget_create.html'
    success_url = reverse_lazy('budget:budget_list')
    
    def get_queryset(self):
        qs = super(BudgetUpdateView, self).get_queryset()
        return qs.filter(user=self.request.user) 

class BudgetDeleteView(LoginRequiredMixin,DeleteView):
    model = Budget
    
    fields = ['name', 'income', 'expenses', 'is_monthly', 'is_weekly']
    success_url = reverse_lazy('budget:budget_list')

    def get_queryset(self):
        qs = super(BudgetDeleteView, self).get_queryset()
        return qs.filter(user=self.request.user)
    
class SearchResultsList(LoginRequiredMixin  ,generic.ListView):
    model = Budget
    context_object_name = 'budget'
    template_name = 'budget/budget_search.html'

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query != '':
            return Budget.objects.filter(user=self.request.user).filter(name__icontains=query)
        
class BusinessCreateView(CreateView):
    model = BusinessMessage
    fields = ['email', 'phone', 'message']
    template_name = 'budget/business_create.html'
    success_url = reverse_lazy('store:home')
#begin savings goal list, detail, crud views

class SavingsGoalListView(LoginRequiredMixin,generic.ListView):
    model = SavingsGoal
    context_object_name = 'goals'
    template_name = 'budget/savings-goals/goals_list.html'

    def get_queryset(self):
        return SavingsGoal.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        income = Budget.objects.all().filter(user=self.request.user).aggregate(Sum('income')).pop('income__sum')
        expenses = Budget.objects.all().filter(user=self.request.user).aggregate(Sum('expenses')).pop('expenses__sum')
        current_goal = SavingsGoal.objects.all().filter(user=self.request.user).aggregate(Sum('goal')).pop('goal__sum')
        goals = SavingsGoal.objects.all().filter(user=self.request.user)
        debt_total = Debt.objects.all().filter(user=self.request.user).aggregate(Sum('amount')).pop('amount__sum')
        
        if current_goal is not None:
            context['current_goal'] = current_goal

        if debt_total is not None:
            context['debt_total'] = debt_total
        if goals is not None:
            context['goals'] = goals
        if income is not None:
            if expenses is not None:
                total = int(income-expenses)
                context["net_total"] = total
            else:
                context["net_total"] = 0

       
         
        return context
    
    
class SavingsGoalsDetailView(LoginRequiredMixin,generic.DetailView):
     model = SavingsGoal
     context_object_name = 'goals'
     template_name='budget/savings-goals/goals_detail.html'

     def get_queryset(self):
        return SavingsGoal.objects.filter(user=self.request.user)
     def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        yearly_goal = SavingsGoal.objects.all().filter(user=self.request.user).aggregate(Sum('goal')).pop('goal__sum')
        if yearly_goal is not None:
            
            context['yearly_goal'] = int(yearly_goal)
            
             
             
          
        return context
#begin crud views for savings goals

class SavingsGoalCreate(LoginRequiredMixin,CreateView):
     model = SavingsGoal
     fields = ['name', 'goal', 'deadline']
     success_url = reverse_lazy('budget:savings-goals')
     template_name = 'budget/savings-goals/goals_create.html'

     def form_valid(self, form):
          object = form.save(commit=False)
          object.user = self.request.user
          object.save()
          return super(SavingsGoalCreate, self).form_valid(form)
     
class SavingsGoalUpdate(LoginRequiredMixin,UpdateView):
     model = SavingsGoal
     fields= ['name', 'goal', 'deadline']
     success_url = reverse_lazy('budget:savings-goals')
     template_name  = 'budget/savings-goals/goals_create.html'

     def get_queryset(self):
        qs = super(SavingsGoalUpdate, self).get_queryset()
        return qs.filter(user=self.request.user)
     
class SavingsGoalDelete(LoginRequiredMixin,DeleteView):
     model = SavingsGoal
     fields = ['name', 'goal', 'deadline']
     template_name = 'budget/savings-goals/goals_delete.html'
     success_url = reverse_lazy('budget:savings-goals')

     def get_queryset(self):
        qs = super(SavingsGoalDelete, self).get_queryset()
        return qs.filter(user=self.request.user)
     
#begin debt list and detail views
class DebtListView(LoginRequiredMixin,generic.ListView):
    model = Debt
    context_object_name = 'debt'
    template_name = 'budget/debt/debt_list.html'
    

    def get_queryset(self):
        return Debt.objects.filter(user=self.request.user)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        savings_goal = SavingsGoal.objects.all().filter(user=self.request.user).aggregate(Sum('goal')).pop('goal__sum')
        income = Budget.objects.all().filter(user=self.request.user).aggregate(Sum('income')).pop('income__sum')
        expenses = Budget.objects.all().filter(user=self.request.user).aggregate(Sum('expenses')).pop('expenses__sum')
        debt_total = Debt.objects.all().filter(user=self.request.user).aggregate(Sum('amount')).pop('amount__sum')

        if income is not None:
            if expenses is not None:
                total = income - expenses
                context['overall_total'] = int(total)

        if debt_total is not None:
            context['debt_total'] = debt_total
        context["qs"] = Debt.objects.all().filter(user=self.request.user)
        context['savings_goal'] = savings_goal
        return context
    
    
class DebtDetailView(LoginRequiredMixin ,generic.DetailView):
    model = Debt
    context_object_name = 'debt'
    template_name='budget/debt/debt_detail.html'

newportolio/budget/templates/budget/budget_confirm_delete.html
{% extends "budget/index.html"%}
{% block content %}

{% load static %}
{% load humanize %}


{% block styles%}
<link rel="stylesheet" href="{% static 'css/grid.css' %}" />
{% endblock %}




<br>

<div class="container text-center">
    
   
    <div class="row">
      <h3>Delete Budget: {{budget.name}}. <br> id: {{budget.id}}</h3>
      <div class="col-12 col-md-8 fs-2">name: {{budget.name}}</div>
      <div class="col-6 col-md-4">Income: ${{budget.income|intcomma}}</div>
      <div class="col-6 col-md-4">Expenses: ${{budget.expenses|intcomma}}</div>
      <div class="col-6 col-md-4">Created on: ${{budget.creation_date}}</div>
      <div class="col-6 col-md-4">Total: ${{budget.get_total|intcomma}}</div>

  

    <hr>
    <form class= action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        
        {{form.as_table}}
       
        <div class="col-6 col-md-4"> <input class="btn-danger" type="submit" value="Yes, delete."></div>
        
    </form>

<script>
const table = document.querySelector('table');
table.classList.add('table-responsive');
</script>

  </div> <!-- /container -->

</div>
</div>






{% endblock %}

newportolio/budget/templates/budget/budget_create.html
{% extends "budget/index.html"%}

{% block content %}



<br>
<div class="container-fluid text-center">

  

    
<form action="" class="form-inline-responsive bg-dark text-light" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table text-light btn-outline-info table-striped table-lg bg-dark">
        {{form.as_table}}
    </table>
   
    <input type="submit" class="btn btn-primary" value="Submit">
    
    
</form>
<script>
const name = document.getElementById('id_name');
const income = document.getElementById('id_income');
const expense = document.getElementById('id_expenses');






income.classList.add("btn-outline-success");
expense.classList.add('btn-outline-success');
name.classList.add("btn-outline-success");
name.focus();
</script>
        
      </div>
    </div>
  </div>
</div>



</div>


<footer>
    <div class="container text-center">
        <div class="col-6 col-md-4"></div>
        <div class="col-6 col-md-4"></div>
        
    </div>

</footer>





{% endblock %}

newportolio/budget/templates/budget/budget_detail.html
{% extends "budget/index.html"%}
{% block content %}
{% load static %}
{% load humanize%}


{% if budget %}

<div class="container text-center">
  <h3>{{budget.name}}</h3>
  
  <div class="row">
    <div class="col-6 col-md-4"><a href="{% url 'budget:budget_update' budget.id %}">Update Budget</a></div>
    <div class="col-6 col-md-4"><a href="{% url 'budget:budget_delete' budget.id %}">Delete Budget</a></div>

 




  </div>
  <div class="col-12 col-md-8"><a href="{% url 'budget:budget_list'%}">Go back?</a></div>
<br>
</div>

{% else %}
<p> no budgets have been created.</p>

{%endif%}




{% endblock %}

newportolio/budget/templates/budget/budget_list.html
{% extends "budget/index.html"%}
{% block content%}
<section class="features">

{% if budget %}

<div style="width: 800px; margin: 40px auto; background-color: #f9f9f9; padding: 20px; border: 1px solid #ddd; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
  <h2 style="margin-top: 0;">Budget Items</h2>
  <h3>    <button style="background-color: #4CAF50; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;"> <a  href="{% url 'budget:budget_create'%}">Create a new budget item</a></button>
  
  <table id="budget-table" style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
    <thead>
      <tr style="background-color: #f0f0f0; border-bottom: 1px solid #ddd;">
        <th style="padding: 10px; text-align: left; cursor: pointer;" onclick="sortTable(0)">Name</th>
        <th style="padding: 10px; text-align: left; cursor: pointer;" onclick="sortTable(1)">Income</th>
        <th style="padding: 10px; text-align: left; cursor: pointer;" onclick="sortTable(2)">Expenses</th>
        <th style="padding: 10px; text-align: right; cursor: pointer;" onclick="sortTable(3)">Total</th>
      </tr>
    </thead>
    <tbody>
      {% for b in budget %}
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;"><a class="btn btn-info bg-primary text-light bd-highlight" href="{{b.get_absolute_url}}">{{b.name}}</a></td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">{{b.income}}</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd;">{{b.expenses}}</td>
        <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: right;">{{b.get_total}}</td>
        <td><button style="background-color: #03A9F4; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
          <a  href="{% url 'budget:budget_update' b.id%}">Update</a></button></td>
        <td><button style="background-color: #03A9F4; color: #fff; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">
          <a  href="{% url 'budget:budget_delete' b.id%}">Delete</a></button></td>
      </tr>
      {%endfor%}
      
    </tbody>
  </table>
  <div style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ddd;">
    <h3 style="margin-top: 0;">Totals:</h3>
    <p style="margin-bottom: 10px;">Total: {{overall_total}}</p>
    <p style="margin-bottom: 10px;">Expenses: {{expenses}}</p>
    <p style="margin-bottom: 10px;">Income: {{income}}</p>
  </div>
</div>

      {%else %}
      <p>Something is very wrong here</p>


      {% endif %}
</section>
{% endblock content%}
      

newportolio/budget/templates/budget/budget_search.html
{% extends "store/base_generic.html"%}
{% block content %}
{% if budget %}
{% for b in budget%}
<li><a href="{{b.get_absolute_url}}">{{b.name}}</a></li>

{% endfor %}

{% else %}
<p>no results found</p>
{% endif %}
{% endblock %}

newportolio/budget/templates/budget/business_create.html
{% extends "store/base_generic.html" %}
{% block content %}
<br>
<br>

<br>
<div class="container">
    <h2 class='text-success'>Leave a Message</h2>
<form action="" class="form-group bg-dark text-light" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table text-light table-striped table-sm">
        {{form.as_table}}
    </table>
   
    <input type="submit" class="btn btn-primary" value="Submit">
    
</form>
<script>
const table = document.querySelector('table');
table.classList.add('table-responsive');
</script>


{% endblock %}

newportolio/budget/templates/budget/index.html
<!DOCTYPE html>
<html lang="en">
    {% load humanize %}
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Budgeting App</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    {% block styles%}
   
   
    {% endblock %}
    {% block scripts%} 

    {% endblock scripts%}

   <style>

 
</style>
</head>
<body>
    <header>
        
        <nav>
            <ul>
                <li>
                    <a href="{% url 'budget:home'%}">Home</a>
                  </li>
                <li>
                    <a href="{% url 'budget:budget_list'%}">MyBudget</a>
                  </li>
                  <li>
                    <a href="{% url 'budget:savings-goals'%}">MyGoals</a>
                  </li>
                  <li>
                    <a href="{% url 'budget:debt-list'%}">MyDebt</a>
                  </li>
                  {% if user.is_authenticated%}
                  <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                  </form>                
                  
      
                {%else %}
              <a class="dropdown-item" href="{% url 'login'%}?next={{request.path}}">Login</a>
              
              <a class="dropdown-item" href="{% url 'budget:signup'%}">Signup</a>
                  
                {% endif %}

            </ul>
        </nav>
      
    </header>
   
    <main>
        {% block content%}
        
        <section class="hero">
            <h1>Take control of your finances with our budgeting app</h1>
            <p>Track your income, expenses, and savings in one place</p>
            <button><a class="dropdown-item" href="{% url 'budget:signup'%}">Signup</a></button>
        </section>
        <section class="features">
            <h2>Key Features</h2>
            <div class="feature">
                <h3>Track your expenses</h3>
                <p>Monitor your spending habits and stay on top of your finances</p>
            </div>
            <div class="feature">
                <h3>Set savings goals</h3>
                <p>Set targets and work towards achieving your financial objectives</p>
            </div>
            <div class="feature">
                <h3>Get insights into your spending habits</h3>
                <p>Understand where your money is going and make informed decisions</p>
            </div>
        </section>
        <section class="call-to-action">
            <button><a href="{% url 'login'%}">Login to get started.</a></button>
            <button><a href="{% url 'budget:signup'%}">Sign up for free</a></button>
        </section>
        {% endblock content%}
    </main>
 
    <footer>
        <p>&copy; 2024 Budgeting App</p>
        <ul>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Terms of Service</a></li>
        </ul>
    </footer>
</body>
</html>

newportolio/budget/templates/budget/login.html
{% extends "store/base_generic.html"%}
{% load static %}
{% block styles %}
<link rel='stylesheet' href="{% static 'css/signin.css' %}">
{% endblock %}
{% block content %}
<div class="container-fluid text-center">
<p>hello world</p>
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
  <p>Your account doesn't have access to this page. To proceed,
  please login with an account that has access.</p>
{% else %}
  <p>Welcome, please login</p>
{% endif %}
{% endif %}


  <form class="form-signin-responsive" method="post" action="{% url 'login' %}">
    {% csrf_token %}

    
    <img class="mb-4" src="{% static 'images/hand.jpg' %}" alt="" width="400" height="auto">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

  {{form.username.label_tag}}
    {{ form.username }}

{{form.password.label_tag}}
    {{ form.password }}
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    <input class="btn btn-lg btn-primary btn-block" type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>
 
  <script>
    const username = document.getElementById('id_username');
    const password = document.getElementById('id_password');
  
    username.classList.add("form-control");
    password.classList.add("form-control");
  </script>


</div>
<!--
    
<img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
<h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
<input type="email" name="username" id="inputEmail" class="form-control" placeholder="Email address" autocomplete="username" required id="id_username" value="{}" required autofocus>

<input type="password" id="password" class="form-control" placeholder="Password" autocomplete="current-password" required id="id_password" required>


-->










{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>
<p><a href="{% url 'store:signup' %}">Create account?</a></p>


{% endblock %}

newportolio/budget/templates/budget/user_signup.html
{% extends "budget/index.html"%}
{% load static%}
{% block styles %}
<link rel='stylesheet' href="{% static 'css/signin.css' %}">
{% endblock %}
{% block content %}
<br>
<br>


{% if next %}
{% if user.is_authenticated %}
  <p class="text-danger">Your account doesn't have access to this page. To proceed,
  please login with an account that has access.</p>
{% else %}
  <p>Please login to see this page.</p>
{% endif %}
{% endif %}
<body class="text-center">
  <br>
  <div class="container">

  </div>
  {% if form.errors %}
<div class="container">
  <p class="text-danger">Your username and password didn't match. Please try again. error {{form.errors}}</p>
<p>galleric</p>
</div>
{% endif %}
  <form class="form-signin" method="post" action="{% url 'budget:signup' %}">
    {% csrf_token %}

    
 {{form.as_table}}
 <input class="btn btn-lg btn-primary btn-block" type="submit" value="login">
 <input type="hidden" name="next" value="{{ next }}">
  </form>
 
  <script>
    const username = document.getElementById('id_email');
    const pass1 = document.getElementById('id_password1');
    const pass2 = document.getElementById('id_password2');

    username.classList.add("form-control");
    pass1.classList.add("form-control");
    pass2.classList.add("form-control");

  </script>
</body>
















{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}